chore: update ESLint and Prettier configurations, add new plugins, and refine TypeScript settings
- Updated Prettier configuration for improved formatting rules.
- Enhanced ESLint configuration with new plugins: boundaries, prettier, and simple-import-sort.
- Adjusted TypeScript settings for stricter type checking and module detection.
- Modified Vite configuration to include server settings and preview options.
- Improved Husky pre-commit hook for linting and formatting checks.
- Refactored various components and application structure for better organization.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,9 @@
-npm test
+echo "🔍🎨 Linting and formatting staged files before commit..." 
+
+npx lint-staged
+if [ $? -ne 0 ]; then
+  echo "💀❌ Lint failed! Check out errors from console and fix it before commit"
+  exit 1
+fi
+
+echo "🥳✅ Formatting and linting process completed!"
